name: fire-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cx_oracle=7.0
  - sqlalchemy=1.2.13
  - pyproj
  - gama
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - black
  - pylint
  - sqlalchemy_schemadisplay
