version: 2
jobs:
  build:
    docker:
       - image: oraclelinux:7
#      - image: circleci/python:3.6.7
#      - image: septimaps/oracle-12c-bootstrapped
    steps:
      - checkout
      - run:
          name: Update Oracle Linux yum server repo
          command: |
            cd /etc/yum.repos.d
            mv public-yum-ol7.repo public-yum-ol7.repo.bak  
            wget http://yum.oracle.com/public-yum-ol7.repo
      - run:
          name: Update Oracle Linux yum server repo
          command: |
            cd /etc/yum.repos.d
            mv public-yum-ol7.repo public-yum-ol7.repo.bak  
            wget http://yum.oracle.com/public-yum-ol7.repo
      - run:
          name: Enable Oracle Linux yum server repo
          command: |
            yum install -y yum-utils
            yum-config-manager --enable ol7_oracle_instantclient
      - run:
          name: Install Oracle Linux deps
          command: |
            yum -y install nmap oracle-instantclient18.3-basic.x86_64
      - run:
          name: nmap localhost
          command: |
            nmap localhost
