version: 2
jobs:
  build:
    docker:
       - image: oraclelinux:7
#      - image: circleci/python:3.6.7
#      - image: septimaps/oracle-12c-bootstrapped
    steps:
      - checkout
      - run:
          name: Install Oracle Linux dependencies
          command: yum install nmap
#      - setup_remote_docker: 
#          docker_layer_caching: true
      - run:
          name: nmap localhost
          command: |
            nmap localhost
