version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch
      - image: 478520491926.dkr.ecr.eu-central-1.amazonaws.com/fikspunktsregister
    steps:
      - checkout
      - run:
          name: Install Debian dependencies
          command: sudo apt install python-pip nmap
#      - setup_remote_docker: 
#          docker_layer_caching: true
      - run:
          name: nmap localhost
          command: |
            nmap localhost
