version: 2
jobs:
  build:
    docker:
       - image: oraclelinux:7
#      - image: circleci/python:3.6.7
#      - image: septimaps/oracle-12c-bootstrapped
    steps:
      - checkout
      - run:
          name: Install Oracle Linux deps
          command: |
            yum -y install wget sudo python-pip
      - run:
          name: Update Oracle Linux yum server repo
          command: |
            cd /etc/yum.repos.d
            mv public-yum-ol7.repo public-yum-ol7.repo.bak  
            wget http://yum.oracle.com/public-yum-ol7.repo
      - run:
          name: Update Oracle Linux yum server repo
          command: |
            cd /etc/yum.repos.d
            mv public-yum-ol7.repo public-yum-ol7.repo.bak  
            wget http://yum.oracle.com/public-yum-ol7.repo
      - run:
          name: Enable Oracle Linux yum server repo
          command: |
            yum install -y yum-utils
            yum-config-manager --enable ol7_developer_EPEL ol7_oracle_instantclient
      - run:
          name: Install Oracle Linux deps
          command: |
            yum -y install python36 python36-pip oracle-instantclient18.3-basiclite.x86_64
            python3.6 -m venv py36env
            source py36env/bin/activate
      - run:
          name: Install cx_Oracle
          command: |
            python -m pip install cx_Oracle --upgrade
      - run:
          name: Initialize schema
          command: |
            python ....
