version: 2
jobs:
  build:
    docker:
      - image: oraclelinux:7
      - image: septimaps/oracle-12c-bootstrapped
    steps:
      - checkout
      - run:
          name: Setup Oracle Linux 7 with instant client and Python 3.6
          command: test/setup.sh
      - run:
          name: Execute init.sql
          command: |
            sqlplus64 -S system/oracle@//localhost:1521/xe @test/sql/init.sql